### ISSUE TITLE
I keep getting nothing to scrape

### ISSUE THREAD

**Issue by Bigchaor** [DIGITALCRIMINAL/OnlyFans#746] opened 2021-01-22 13:28 UTC
I keep looping withthis error:

Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.0 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit

**Comment by Backaache** [comment] 2021-01-23 03:23
Try cloning the master branch.

**Comment by kingtiger20** [comment] 2021-01-23 19:50
Also having this issue with the master branch

**Comment by chidi9901** [comment] 2021-01-23 23:25
Your "active" is set to "true"?

**Comment by bluebower** [comment] 2021-01-24 02:11
Thanks @chidi9901, setting `"active": true` in auth.json worked for me.

**Comment by Idesmi** [comment] 2021-01-25 09:58
Why did you close it? The issue is not solved.

**Comment by bluebower** [comment] 2021-01-25 10:13
I had the same error as OP, and a solution was posted.

**Comment by DIGITALCRIMINAL** [comment] 2021-01-25 15:55
> Why did you close it? The issue is not solved.
> 
> auth.json keeps getting rewritten with "default" as user

This has been talked about 1000000000000000000 times. Just use the search function.

**Closed by DIGITALCRIMINAL** 2021-01-25 15:55 UTC
