### ISSUE TITLE
How do you migrate the saved folder between versions?

### ISSUE THREAD

**Issue by goodboi69** [DIGITALCRIMINAL/OnlyFans#316] opened 2020-07-03 12:33 UTC
I was using 5.0 and copied the .sites save folder, with the metadata, into the new 5.1 folder and I got an error stating it couldn't find the path for 5.0. So I had to rename the 5.1 folder to 5.0. How do you migrate the saves between versions of the program?

**Comment by herefromrdt** [comment] 2020-07-04 04:30
The old path is still in all of the json metadata files in the .site folder. I opened the folder in VS code and did a find/replace on the old path to the new path. 
The current setup doesn't really seem to support switching download directories.

**Comment by herefromrdt** [comment] 2020-07-04 04:32
Also, I think this is a duplicate of #301

**Comment by docholllidae2** [comment] 2020-07-04 17:37
@herefromrdt what did your old/does your new directory structure look like?
I'm having a similar issue #310 

I don't have a metadata folder in the root of the model directory, but instead several, each in its own directory according to post type. I tried editing the `.json` file to have the new download path but I am still having issues

**Comment by DIGITALCRIMINAL** [comment] 2020-07-06 20:03
oof, I never thought of this problem because my directory structure remains the same

**Comment by DIGITALCRIMINAL** [comment] 2020-07-06 20:04
I remember the individual metadata like Post.json, etc. It's somewhat incompatible, but I'll see what I can do.

**Closed** 2020-07-07 14:53 UTC
