### ISSUE TITLE
Authentication not working?

### ISSUE THREAD

**Issue by mwald84** [DIGITALCRIMINAL/OnlyFans#342] opened 2020-07-26 14:58 UTC
Since this morning the app seems to be failing in the authentication for me.

The JSON file (the one with posts count and etc) returning is:

    {'error': {'code': 401, 'message': 'Request sign required'}}

Checking the app token and cookies, they look the same I have on my `config.json` so probably OnlyFans changed auth again.

Let me know if I can send more info to help track the issue.

Thanks.

Marcos

**Comment by shinji257** [comment] 2020-07-26 16:39
Likely duplicate of #341

**Comment by mwald84** [comment] 2020-07-26 17:18
I actually can see the auth hash on my browser. I thought that was the issue in #341

**Closed** 2020-07-26 17:20 UTC
