### ISSUE TITLE
Did i get pinched, or is there something I missed?

### ISSUE THREAD

**Issue by James-MF-Thomas** [DIGITALCRIMINAL/OnlyFans#627] opened 2020-12-25 05:04 UTC
![Screen Shot2](https://user-images.githubusercontent.com/47627618/103120321-d9251400-463c-11eb-8173-94d70c5c90a8.png)

![Screen Shot 2020-12-24 at 10 55 15 PM](https://user-images.githubusercontent.com/47627618/103120177-42f0ee00-463c-11eb-8505-1feaf86d0157.png)

**Comment by James-MF-Thomas** [comment] 2020-12-25 05:06
well I definitely missed some ip's, but whatever running a VPN anyway

**Comment by ProjektPremium** [comment] 2020-12-25 08:24
Don't use a VPN or Proxy.

**Comment by James-MF-Thomas** [comment] 2020-12-25 08:29
I wasn’t using one during the original scrape. I turned on the vpn for the post. 

I was actually getting 403’d from OnlyFans when this started yesterday.  They only way I could login successfully was via vpn. Now today I can login either way successfully but I’m still stuck in that loop either way ( with or without a vpn)

**Comment by ProjektPremium** [comment] 2020-12-25 13:02
Go back to a previous version I would suggest and see if it makes any difference. Every time I have had a problem that doesn't involve any code changes but would seem like a "technical" problem, I go back to a previous version and see if I have any problems. Most of the time I'm using 5.5

**Comment by DIGITALCRIMINAL** [comment] 2020-12-25 14:12
> I wasn’t using one during the original scrape. I turned on the vpn for the post. 
> 
> I was actually getting 403’d from OnlyFans when this started yesterday.  They only way I could login successfully was via vpn. Now today I can login either way successfully but I’m still stuck in that loop either way ( with or without a vpn)

Can you login via the site without a VPN

**Comment by James-MF-Thomas** [comment] 2020-12-25 14:44
Yes today I can. I couldn’t for idk 12-24hrs but now no vpn needed for the web browser.  Python is still stuck in that loop though.

**Comment by TheSafecracker** [comment] 2020-12-25 15:02
Just came here to check to see if I was alone. I'm getting the same results as James. No changes since last night, when I last ran it successfully.

**Comment by James-MF-Thomas** [comment] 2020-12-25 17:25
Running v5.9.1 results:

![Screen Shot 2020-12-25 at 11 22 45 AM](https://user-images.githubusercontent.com/47627618/103139620-b4b05280-46a3-11eb-912e-b817ebc00315.png)
![Screen Shot 2020-12-25 at 11 22 30 AM](https://user-images.githubusercontent.com/47627618/103139628-c2fe6e80-46a3-11eb-8e1a-37a1c9dc5b63.png)
![Screen Shot 2020-12-25 at 11 21 23 AM](https://user-images.githubusercontent.com/47627618/103139637-cbef4000-46a3-11eb-9f99-7508a13edbf9.png)

My account is a "creator" account if that's relative.

**Comment by James-MF-Thomas** [comment] 2020-12-25 17:33
Running v5.5 results:

successful:
![Screen Shot 2020-12-25 at 11 32 13 AM](https://user-images.githubusercontent.com/47627618/103139748-09080200-46a5-11eb-8042-bd669811b215.png)

**Comment by DIGITALCRIMINAL** [comment] 2020-12-25 19:44
Duplicate of https://github.com/DIGITALCRIMINAL/OnlyFans/issues/621

This is the information I need to know.
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/621#issuecomment-751167183

**Closed by DIGITALCRIMINAL** 2020-12-25 19:44 UTC
