### ISSUE TITLE
renamer script not working

### ISSUE THREAD

**Issue by docholllidae2** [DIGITALCRIMINAL/OnlyFans#310] opened 2020-07-01 16:46 UTC
I'm on version 5.1, and when I try to download a model's page it shows me this error:
```
2020-07-01 12:30:34,711 ERROR errors [WinError 3] The system cannot find the path specified: 'D:\\Downloads\\.tools\\OnlyFans\\.sites\\OnlyFans\\harleymichelle\\Posts\\Free\\Images'
Traceback (most recent call last):
  File "D:\Downloads\.tools\OnlyFans\datascraper\main_datascraper.py", line 186, in start_datascraper
    result = x.start_datascraper(
  File "D:\Downloads\.tools\OnlyFans\modules\onlyfans.py", line 92, in start_datascraper
    results = prepare_scraper(
  File "D:\Downloads\.tools\OnlyFans\modules\onlyfans.py", line 512, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "D:\Downloads\.tools\OnlyFans\helpers\main_helper.py", line 101, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "D:\Downloads\.tools\OnlyFans\extras\OFRenamer\start.py", line 79, in start
    metadata.valid = fix_metadata(
  File "D:\Downloads\.tools\OnlyFans\extras\OFRenamer\start.py", line 64, in fix_metadata
    files = os.listdir(folder)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Downloads\\.tools\\OnlyFans\\.sites\\OnlyFans\\harleymichelle\\Posts\\Free\\Images'
```
That is with `"sort_free_paid_posts": false,`
If I set it to `true` it simply re-downloads everything from scratch

I also tried to run the renamer script directly and I get this error message:
```
Traceback (most recent call last):
  File "start.py", line 148, in <module>
    start(metadata_filepath, json_settings)
  File "start.py", line 79, in start
    metadata.valid = fix_metadata(
  File "start.py", line 64, in fix_metadata
    files = os.listdir(folder)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Downloads\\.tools\\OnlyFans\\.sites\\OnlyFans\\harleymichelle\\Posts\\Free\\Images'
```

 I had downloaded all her content before upgrading to the new version, so nothing is sorted into `free` or `paid` folders
(p.s.  the readme says that if I set `"sort_free_paid_posts": false,` it will be incompatible ... how so/incompatible with what?)

Here is the filename format I was using previously:
```
"directory": "./downloads",
 "file_name_format": "{username}/{date}_~_{text}_~_{file_name}.{ext}",
```

And per suggestions I had seen, my new filename format:
```
"download_path": "./{site_name}",
"file_name_format": "{username}/{date}_{post_id}_{media_id}~~~{file_name}.{ext}",
```

As an aside, while I will keep `{text}` out of the file-naming going forward, how do you all add any kind of context to the files so that you know what each file is/about? (b/g scenes, g/g scenes, solo scenes, etc)

**Comment by docholllidae** [comment] 2020-07-01 16:50
Do the model directories need to have a specific file structure for the renamer to work properly?
In previous versions I was using this (the first `OnlyFans` being the root script dir):
`OnlyFans\downloads\onlyfans\{username}\`
`OnlyFans\downloads\stars_avn\{username}\`

now it looks like this:
`OnlyFans\.sites\OnlyFans\{username}\`

I tried copying the model's folder into the new directory structure

**Comment by DIGITALCRIMINAL** [comment] 2020-07-01 20:33
> I had downloaded all her content before upgrading to the new version, so nothing is sorted into `free` or `paid` folders
> (p.s. the readme says that if I set `"sort_free_paid_posts": false,` it will be incompatible ... how so/incompatible with what?)

Incompatible with the whole script and which would create errors.
You should just set it to true. The whole script is built around free/paid file structure now.

The script already moves everything that wasn't deleted by the model to the new file structure anyway.

The download_path should be using a full path instead of "./" or use two dots instead of one.

**Comment by docholllidae2** [comment] 2020-07-01 22:55
So here is my whole config for OF:
```
      "settings": {
        "auto_choice": "a",
        "auto_scrape_names": false,
        "auto_scrape_apis": true,
        "download_path": "D:/Downloads/.tools/OnlyFans/downloads/{site_name}",
        "file_name_format": "{username}/{date}_{post_id}_{media_id}~~~{file_name}.{ext}",
        "text_length": "42",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": true,
        "blacklist_name": ""
      },
      "extra_auth_settings": {
        "extra_auth": false,
        "choose_auth": false,
        "merge_auth": false
```

It is re-downloading everything instead of renaming
Is the renamer script meant only to rename posts already in the new (free/paid) format, or to also rename/move files from the old format? 

When I run the renamer separately I get this error
```
Traceback (most recent call last):
  File "start.py", line 143, in <module>
    folders = os.listdir(metadata_directory)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:/Downloads/.tools/OnlyFans/downloads/OnlyFans\\allybabyxo6\\Metadata'
```

**Comment by DIGITALCRIMINAL** [comment] 2020-07-02 05:14
What is the correct full path of allybaby?

**Comment by docholllidae** [comment] 2020-07-02 05:42
`D:/Downloads/.tools/OnlyFans/downloads/OnlyFans/allybabyxo6`

**Comment by DIGITALCRIMINAL** [comment] 2020-07-02 05:43
Are you not subscribed to allybabyxo6 anymore?

**Comment by docholllidae** [comment] 2020-07-02 05:44
no not anymore. I thought it would just skip over the ones I'm not sub'd to though

**Comment by DIGITALCRIMINAL** [comment] 2020-07-02 06:03
in the image folder of allybabyx06, is there a metadata folder

**Comment by docholllidae2** [comment] 2020-07-02 18:27
There is not

The default folder structure for all the models I've subscribed to do far is
```
{username}
    Messages
        Audios
            File.mp3
        Metadata
        Images
        Videos
    Posts
    Stories

**Comment by DIGITALCRIMINAL** [comment] 2020-07-02 18:28
Closed by mistake?

**Comment by docholllidae2** [comment] 2020-07-02 18:32
Yes haha. I updated my comment too not sure if you saw that

**Comment by UnstoppableMango** [comment] 2020-07-02 19:16
I think I have a similar issue, and it may be because I borked my config. Just updated today and I didn't read too closely and assumed "download_path" would append "OnlyFans" as (I believe?) it did previously. So where before I had model folders at "/mnt/isos/OnlyFans", model folders were getting put at "/mnt/isos". I aborted the script and attempted to use rsync to fix my mistakes. Re-running the scraper resulted in the same exception above.

In the Metadata folder at the root of the model folder, so "/mnt/isos/OnlyFans/{model}/Metadata", the .json files had the incorrect path rooted at "/mnt/isos".

Not sure if this helps @docholllidae2. May need to fix paths in the metadata json? I'm not sure how the internals of the scraper work.

**Comment by mwald84** [comment] 2020-07-02 22:59
I'm having this issue and I think it may be related to the use of {text} on filename. It seems to be caused by invalid chars in the text to name a file.

**Comment by docholllidae2** [comment] 2020-07-03 05:24
Hmmm I will try checking my metadatas, though there is not any metadata folder in the root of the model folder for me; there are several, one in each of the post type's folder (one in `posts` another in `messages` and one in `stories`)

**Comment by docholllidae2** [comment] 2020-07-03 14:00
I still get that same error when

**Comment by docholllidae2** [comment] 2020-07-03 14:01
Again I accidentally tapped close. I need to stop doing this on mobile. 

I updated the metadata .json files with the full and correct path but still get that same error when running the renamed

**Comment by docholllidae2** [comment] 2020-07-04 19:09
if it matters, the version I was on previously was 4.0

**Comment by UnstoppableMango** [comment] 2020-07-04 22:51
I went through every Metadata json I could find and corrected the download path and that fixed it for me

**Comment by DIGITALCRIMINAL** [comment] 2020-07-07 16:04
Use the latest commit

**Comment by docholllidae2** [comment] 2020-07-07 18:51
I just tried the latest commit, and it still downloads everything fresh instead of renaming.  
How does the renamer work? Does it look for `metadata` folder in the root of the model directory? None of my model directories have one there; they are all in their post types (eg `model\Posts\metadata\` and `model\Messages\metadata`)

start_ofd.py creates a `model\metadata\` folder, but the newly-created `Posts.json` points to the also newl-created `model\Posts\Free\Images` folder

Should it check for `model\Posts\metadata\Images.json` and `model\Posts\Images\file.jpg` instead and move and rename files from there?

Also, when I run the renamer directly now I get this error
```
Traceback (most recent call last):
  File "start.py", line 149, in <module>
    for models_folder in content_folders:
NameError: name 'content_folders' is not defined
```

**Comment by DIGITALCRIMINAL** [comment] 2020-07-07 19:28
@docholllidae2 oh ye, is the model\metadata folder empty?

**Comment by DIGITALCRIMINAL** [comment] 2020-07-07 19:30
@docholllidae my bad, I pushed a commit to uncomment this line

![image](https://user-images.githubusercontent.com/21285176/86832829-9b353300-c090-11ea-9b24-56ca77ae6e3a.png)


You can either download the commit again or just uncomment the line.

**Comment by docholllidae2** [comment] 2020-07-07 19:32
> @docholllidae2 oh ye, is the model\metadata folder empty?

there is no model\metadata

all of them are from v4.0 or earlier, before you implemented a root model metadata

**Comment by DIGITALCRIMINAL** [comment] 2020-07-07 19:34
ohh ye, try running the ofrenamer directly and it should fix it

**Comment by docholllidae2** [comment] 2020-07-07 19:56
> ohh ye, try running the ofrenamer directly and it should fix it

ok, so it's finally operating on the files, but now it fills my terminal with these messages for each model
```
FOUND: D:/Downloads/.tools/OnlyFans/downloads/OnlyFans\harleymichelle\Posts\Videos
NOT FOUND: D:\Downloads\.tools\OnlyFans\extras\OFRenamer\downloads\OnlyFans\harleymichelle\Posts\Videos
FOUND: D:/Downloads/.tools/OnlyFans/downloads/OnlyFans\harleymichelle\Posts\Videos
NOT FOUND: D:\Downloads\.tools\OnlyFans\extras\OFRenamer\downloads\OnlyFans\harleymichelle\Posts\Videos
FOUND: D:/Downloads/.tools/OnlyFans/downloads/OnlyFans\harleymichelle\Posts\Videos
NOT FOUND: D:\Downloads\.tools\OnlyFans\extras\OFRenamer\downloads\OnlyFans\harleymichelle\Posts\Images
```

It also is putting every file it renames into the root model directory

**Comment by DIGITALCRIMINAL** [comment] 2020-07-07 20:05
@docholllidae is it copying it to the root model folder?

**Comment by docholllidae2** [comment] 2020-07-07 20:20
It's moving to the root folder

I do have previous versions on windows enabled, so I can revert all the changes if need be

**Comment by DIGITALCRIMINAL** [comment] 2020-07-07 21:02
It should be fixed now

**Comment by docholllidae2** [comment] 2020-07-07 21:19
should I restore the previous version of the files or keep them in the root directory and run again?

**Comment by DIGITALCRIMINAL** [comment] 2020-07-07 21:20
Gonna have to restore :/

**Comment by docholllidae2** [comment] 2020-07-07 21:44
Ok, This will be a few hours

**Comment by docholllidae2** [comment] 2020-07-08 17:16
Hmmm, I'm now getting this error running ofrenamer directly

```
Traceback (most recent call last):
  File "start.py", line 123, in <module>
    x = int(input())
ValueError: invalid literal for int() with base 10: ''
```

**Comment by DIGITALCRIMINAL** [comment] 2020-07-08 17:21
> Hmmm, I'm now getting this error running ofrenamer directly
> 
> ```
> Traceback (most recent call last):
>   File "start.py", line 123, in <module>
>     x = int(input())
> ValueError: invalid literal for int() with base 10: ''
> ```

Input a number and don't press enter?

**Comment by docholllidae2** [comment] 2020-07-08 17:58
My bad, I was going too fast and didn't realize numlock was off
It now throws this error, presumably on the first media file it's trying to process

```
NOT FOUND: D:\Downloads\.tools\OnlyFans\extras\OFRenamer\downloads\OnlyFans\baby_sweetness\Archived\Images
FOUND: D:/Downloads/.tools/OnlyFans/downloads/OnlyFans\baby_sweetness\Archived\Images
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\shutil.py", line 781, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Downloads\\.tools\\OnlyFans\\downloads\\OnlyFans\\baby_sweetness\\Archived\\Images\\2020-04-8_~_Nasty_Bougie_Classy_~_2048x1536_d4ce29d11bcf482051d3156c1f4b6bb3.jpg' -> D:\\Downloads\\.tools\\OnlyFans\\downloads\\OnlyFans\\baby_sweetness\\Archived\\Images\\baby_sweetness\\2020-04-28_21105147_~~~2048x1536_d4ce29d11bcf482051d3156c1f4b6bb3.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 188, in <module>
    start(metadata_filepath, json_settings)
  File "start.py", line 90, in start
    metadata.valid = fix_metadata(
  File "start.py", line 79, in fix_metadata
    filepath = update(filepath)
  File "start.py", line 59, in update
    shutil.move(filepath, new_format)
  File "C:\Program Files\Python38\lib\shutil.py", line 795, in move
    copy_function(src, real_dst)
  File "C:\Program Files\Python38\lib\shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Python38\lib\shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Downloads\\.tools\\OnlyFans\\downloads\\OnlyFans\\baby_sweetness\\Archived\\Images\\baby_sweetness\\2020-04-28_21105147_~~~2048x1536_d4ce29d11bcf482051d3156c1f4b6bb3.jpg'

**Comment by DIGITALCRIMINAL** [comment] 2020-07-08 18:01
Is that the correct directory in the error?
`D:\\Downloads\\.tools\\OnlyFans\\downloads\\OnlyFans\\baby_sweetness\\Archived\\Images\\baby_sweetness\\`

**Comment by docholllidae2** [comment] 2020-07-08 18:47
> Is that the correct directory in the error?
> `D:\\Downloads\\.tools\\OnlyFans\\downloads\\OnlyFans\\baby_sweetness\\Archived\\Images\\baby_sweetness\\`

No; it looks like it's trying to create a new directory of the model to move/rename the images into?

But that directory does not exist, it is just `baby_sweetness\Archived\Images\files.jpg`

**Comment by DIGITALCRIMINAL** [comment] 2020-07-08 21:50
I wouldn't know what to do unless you send me the metadata file via email

**Comment by docholllidae2** [comment] 2020-07-09 15:38
Ok, here's a link to 0-byte file and full directory structure, so you can see just exactly how everything is set up. My (sanitized) config file is included  
https://mega.nz/folder/OME2jYgQ#95X9QJQ4RdXWs0-G3ZEk8g

And I will email you the metadata file as well

**Comment by wanyek43** [comment] 2020-08-07 17:07
Having the same or similar issue here on mac ever since I pulled the latest commit about two weeks ago. Was previously using version 3.9, and skipped version 4 right to 5.1. I just updated it to 5.2 yesterday, but am still having the issue.

Terminal output:
`Scrape Processing
Name: OFUSER
Type: Stories
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
FOUND: /Volumes/Videos/.private/Scraper/OnlyFans/OFUSER/Stories/Free/Videos
FOUND: /Volumes/Videos/.private/Scraper/OnlyFans/OFUSER/Stories/Free/Videos
Type: Highlights
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Type: Posts
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
FOUND: /Volumes/Videos/.private/Scraper/OnlyFans/OFUSER/Posts/Free/Images
FOUND: /Volumes/Videos/.private/Scraper/OnlyFans/OFUSER/Posts/Free/Images
2020-08-07 09:56:06,843 ERROR errors [Errno 2] No such file or directory: '/Volumes/Videos/.private/Scraper/OnlyFans/OFUSER/Posts/Free/Images/OFUSER/2020-07-28-772x948_88175048728413c91d5e1e482e078714.jpg'
Traceback (most recent call last):
  File "/Users/USER/.pyenv/versions/3.8.3/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Videos/.private/Scraper/OnlyFans/OFUSER/Posts/Free/Images/2020-07-28-772x948_88175048728413c91d5e1e482e078714.jpg' -> '/Volumes/Videos/.private/Scraper/OnlyFans/OFUSER/Posts/Free/Images/OFUSER/2020-07-28-772x948_88175048728413c91d5e1e482e078714.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USER/Developer/Python/OnlyFans/datascraper/main_datascraper.py", line 229, in start_datascraper
    result = x.start_datascraper(
  File "/Users/USER/Developer/Python/OnlyFans/modules/onlyfans.py", line 100, in start_datascraper
    results = prepare_scraper(
  File "/Users/USER/Developer/Python/OnlyFans/modules/onlyfans.py", line 531, in prepare_scraper
    export_archive(metadata_set, archive_directory, json_settings)
  File "/Users/USER/Developer/Python/OnlyFans/helpers/main_helper.py", line 106, in export_archive
    datas2 = ofrenamer.start(archive_path, json_settings)
  File "/Users/USER/Developer/Python/OnlyFans/extras/OFRenamer/start.py", line 90, in start
    metadata.valid = fix_metadata(
  File "/Users/USER/Developer/Python/OnlyFans/extras/OFRenamer/start.py", line 79, in fix_metadata
    filepath = update(filepath)
  File "/Users/USER/Developer/Python/OnlyFans/extras/OFRenamer/start.py", line 59, in update
    shutil.move(filepath, new_format)
  File "/Users/USER/.pyenv/versions/3.8.3/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/Users/USER/.pyenv/versions/3.8.3/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/USER/.pyenv/versions/3.8.3/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Videos/.private/Scraper/OnlyFans/OFUSER/Posts/Free/Images/OFUSER/2020-07-28-772x948_88175048728413c91d5e1e482e078714.jpg'`

The file it's telling me isn't there is actually at that path.

My config:
`"settings": {
        "auto_choice": "a",
        "auto_scrape_names": false,
        "auto_scrape_apis": true,
        "download_path": "/Volumes/Videos/.private/Scraper/OnlyFans",
        "file_name_format": "{username}/{date}-{file_name}.{ext}",
        "text_length": "255",
        "overwrite_files": false,
        "date_format": "%Y-%m-%d",
        "ignored_keywords": [],
        "ignore_type": "",
        "export_metadata": true,
        "delete_legacy_metadata": false,
        "sort_free_paid_posts": true,
        "blacklist_name": ""
      }`

**Comment by docholllidae2** [comment] 2020-08-07 23:27
It looks like it's appending an extra modelsfolder name to the end, before the filename, where it shouldn't be

**Comment by wanyek43** [comment] 2020-08-13 16:39
> It looks like, when the renamer is looking for the files, it's appending an extra modelsfolder name to the path, before the filename, where it shouldn't be

I've been continually having this issue, but I think I might have found the problem, or at least part of it. You and I have a commonality to our filenames which includes a directory for the username: 

Yours:
`"file_name_format": "{username}/{date}_{post_id}_{media_id}~~~{file_name}.{ext}"`

Mine:
`{username}/{date}-{file_name}.{ext}`

I think that's what's messing it up, the `{username}/` I just removed that part in my config and it's working perfectly. It now looks like this: `"file_name_format": "{date}-{file_name}.{ext}"`

Strange because I've had it like that since I started using the scraper on 3.9 with that same config.

The latest commit does seem to be quite a bit more verbose in its feedback, but it doesn't seem to be duplicating or deleting any of my files. It also seems to still be putting everything into the right place.

**Comment by docholllidae2** [comment] 2020-08-13 20:06
I will try this soon when I'm home. If it works... omg 😮😃😃
I haven't been able to download anything for a month it was throwing that error with even new models

@wanyek43 
Did you move `{username}` into the download directory? Or just remove it entirely?
Does it still autocreate/download to the individual username folder in your download directory?

**Comment by DIGITALCRIMINAL** [comment] 2020-08-13 20:57
Username is automatically created

**Comment by docholllidae2** [comment] 2020-08-13 23:30
The script is downloading again, but it is not renaming any of my old files again, simply re-downloading them

When the renamer is run by itself it does nothing but fill the terminal with these errors (no renaming/moving of the files)

```
D:\Downloads\.tools\OnlyFans\extras\OFRenamer>python start.py
0 = All | 1 = onlyfans | 2 = patreon | 3 = starsavn | 4 = fourchan | 5 = bbwchan
1
NOT FOUND: D:\Downloads\.tools\OnlyFans\extras\OFRenamer\downloads\OnlyFans\baby_sweetness\Archived\Images
FOUND: D:/Downloads/.tools/OnlyFans/downloads/OnlyFans\baby_sweetness\Archived\Images
```

**Comment by wanyek43** [comment] 2020-08-14 00:46
> I will try this soon when I'm home. If it works... omg 😮😃😃
> I haven't been able to download anything for a month it was throwing that error with even new models
> 
> @wanyek43
> Did you move `{username}` into the download directory portion of the config? Or just remove it entirely?
> Does it still autocreate/download to the individual username folder in your download directory?

I removed it completely from the path. All of the new profiles I subscribed to in the last couple of days synced fine and all of the existing ones updated correctly. I've run it twice without duplicates, issue or having to clear out the metadata files. Did you do that before you ran it again with the new path? I deleted the new metadata files (not the old ones) from the previous version of the scraper,  before I ran it again after changing the path.

> Username is automatically created
Yeah I didn't realize that when I first started using the scraper. I've had it like that since 3.9, so that's why I didn't think to change it until I looked closer at the output.

**Comment by docholllidae2** [comment] 2020-08-14 01:48
I have removed `{username}` completely from the config; the models that the renamer fails to run properly against have the metadata in each subfolder only (no master metadata folder). 
But for some reason, it looks like it is looking for a download path in the OFRenamer directory

Figured it out while typing this up:  my old metadata files still had a relative path listed in them from my earlier config settings so the renamer was looking for the files relative to its start.py file.
Replacing the relative path in the metadata files with an absolute path fixed it. So now onto the task of opening each file to do a batch find/replace (unless someone has a more automated way of doing that?)

@DIGITALCRIMINAL 
Would it be possible to build in support for relative paths in the future, in case folders get moved around it doesn't wreak havoc with the scripts?

Anyway, thank you both so much for all the help! @DIGITALCRIMINAL  @wanyek43 
:)

**Comment by DIGITALCRIMINAL** [comment] 2020-08-14 09:54
@docholllidae maybe, but how is your relative path set up?

**Comment by docholllidae2** [comment] 2020-08-14 12:17
I'm not using the relative path anymore, not since the past two months or so, but my subscriptions had barely changed in that time so the majority of my metadata files still had a relative path in them

It was in the download directory however. Here's how it looked when I had it
`        "download_path": "./downloads/{site_name}/{username}",` (but username is now removed entirely of course)

**Comment by docholllidae2** [comment] 2020-08-14 12:51
Also, I just looked and the renamer script is only sort of working (at least according to how I expected it was meant to work). 
It renames the files, but it keeps them in the old directory structure (ie `{downloaddir}\model\posts\images\file.jpg`) rather than moving them into the new free/paid directory format. The downloader now redownloads everything still, into the new structure

Is this intended behavior?

--

My process so far has been:
1. Download model posts (old directory structure (non free/paid), individual metadata folders within each media subtype posts/messages/etc, and relative download_path inside config and metadata .json files, which also point to old directory structure)
2. Changed download path to absolute when upgrading from 4.0 to 5.1
3. With renamer script not running correctly, removed `{username}` from download path, and changed relative path in all old metadata files to absolute path (old metadata files still pointing to old directory structure)
4. Ran renamer script by itself, which kept all files in old directory structure
5. Run downloader which re-downloads all posts into new free/paid structure

I'm unsure if I did something wrong or skipped something somewhere along the way

**Comment by DIGITALCRIMINAL** [comment] 2020-08-14 14:40
You need to set sort_free_paid_posts to true

**Comment by docholllidae2** [comment] 2020-08-14 15:06
it is set true already

**Comment by docholllidae2** [comment] 2020-08-14 15:57
I can send you one of the smaller model folders as it is before running the renamer, and my auth details, if it helps

**Comment by throwaway1228123** [comment] 2020-09-07 09:26
Just to add in, I would like to confirm that I was having the same issue and I too had my settings as `"file_name_format": "{username}/{file_name}.{ext}",` and removing it from the path resolved it for me.

**Closed** 2020-09-29 08:38 UTC
Labels: bug, patching
