### ISSUE TITLE
Sign - session lock/please refresh

### ISSUE THREAD

**Issue by iamnotdev** [DIGITALCRIMINAL/OnlyFans#1202] opened 2021-05-16 12:56 UTC
Here we go again. The sign has changed, need an update :)

**Comment by DIGITALCRIMINAL** [comment] 2021-05-16 13:16
I know, but it's still working

**Comment by sula8** [comment] 2021-05-20 11:14
> I know, but it's still working

It's not working now

**Comment by iamnotdev** [comment] 2021-05-20 11:17
> I know, but it's still working

It's not working now

**Comment by greatmate98** [comment] 2021-05-20 11:55
I was on 7.1 was working yesterday, but got the refresh this page error earlier.  Updated to 7.2...and then the master - and have been getting a slightly different error shown below.  Rather than just looping through the refresh this page on each attempt, it is doing it once, then seemingly working but finding no content.  I am currently subbed to over 100 accounts.  Not a big issue as only have a single account expiring tonight, with only one new vid to nab :)

Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Please refresh the page
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.05 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans |

**Comment by bigbluedeer** [comment] 2021-05-20 13:06
I pulled the newest commits this morning, config file still says its 7.1 though
also this is not working from the browser login either, it will result in this output

`Auth (V1) Attempt 1/10
Please refresh the page
Opening Browser
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 1.76 Minutes
Pausing scraper for 0 seconds.`

**Comment by iamnotdev** [comment] 2021-05-20 13:22
@DIGITALCRIMINAL  I've just applied the updated "sign", but still getting "refresh the page" error

**Comment by hsg120** [comment] 2021-05-20 13:54
Choose Profile
Names: Username = username | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Please refresh the page
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.05 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans |

I can confirm I am getting this same error with 7.2.

**Comment by DIGITALCRIMINAL** [comment] 2021-05-20 13:56
There's literally 0 point to spam the same issue context over and over again.

**Comment by hsg120** [comment] 2021-05-20 13:58
Hey, my bad. Didn't know if further confirmation would be helpful, guess not! Sorry...

**Comment by greatmate98** [comment] 2021-05-20 14:29
Yeah apologies, i thought it looked a different issue since the last time i got the refresh error it gave a different output.

**Comment by iamnotdev** [comment] 2021-05-20 17:57
we are back in game! thanx to @DIGITALCRIMINAL

**Comment by adamperez** [comment] 2021-05-20 19:40
@iamnotdev what was the fix?

**Comment by iamnotdev** [comment] 2021-05-20 22:16
@DIGITALCRIMINAL Not working again 😬

**Comment by Eviepayne** [comment] 2021-05-20 23:13
Got the refresh page error.

**Comment by OFfriend** [comment] 2021-05-20 23:25
v19 change got merged. It works again.

**Comment by atlas-mugged** [comment] 2021-05-20 23:29
Mine working aswell on Ubuntu 20.04! I don't get it though, what fixed it? I don't see an update to 7.2?

**Comment by OFfriend** [comment] 2021-05-20 23:30
> 
> 
> Mine working aswell on Ubuntu 20.04! I don't get it though, what fixed it? I don't see an update to 7.2?

https://github.com/DATAHOARDERS/dynamic-rules/commit/7f0af9d8fa6e7a7219b330bec0c31be1330ccacb

**Comment by Eviepayne** [comment] 2021-05-20 23:31
Working again. SICK

**Comment by mw55309** [comment] 2021-05-25 15:45
It's gone again

**Closed** 2021-05-25 16:11 UTC
