### ISSUE TITLE
Traceback error in latest commit

### ISSUE THREAD

**Issue by headphonia** [DIGITALCRIMINAL/OnlyFans#1262] opened 2021-05-28 11:34 UTC
Getting the following error in the latest commit.

`Traceback (most recent call last):
  File "/start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)

  File "/datascraper/main_datascraper.py", line 102, in start_datascraper
    paid_content = module.paid_content_scraper(api, identifiers)

  File "/modules/onlyfans.py", line 371, in paid_content_scraper
    unrefined_set = media_scraper(
  
File "/modules/onlyfans.py", line 1035, in media_scraper
    post_id = post_result.id

AttributeError: 'list' object has no attribute 'id'`

**Comment by DIGITALCRIMINAL** [comment] 2021-05-28 11:42
Ah I broke scraping paid content. You can turn it off for now.

**Comment by Gixxa** [comment] 2021-05-28 16:03
I also got a error:

Traceback (most recent call last):
  File "D:\OnlyFans-master\start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\OnlyFans-master\datascraper\main_datascraper.py", line 105, in start_datascraper
    names = main_helper.process_names(
  File "D:\OnlyFans-master\helpers\main_helper.py", line 641, in process_names
    result = module.start_datascraper(
  File "D:\OnlyFans-master\modules\onlyfans.py", line 159, in start_datascraper
    results = prepare_scraper(authed, site_name, item)
  File "D:\OnlyFans-master\modules\onlyfans.py", line 792, in prepare_scraper
    unrefined_set = pool.starmap(
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "D:\OnlyFans-master\modules\onlyfans.py", line 1035, in media_scraper
    post_id = post_result.id
AttributeError: 'dict' object has no attribute 'id'

**Comment by HtomSirveaux** [comment] 2021-05-28 16:36
> I also got a error:
> 
> Traceback (most recent call last):
> File "D:\OnlyFans-master\start_ofd.py", line 44, in
> api = main_datascraper.start_datascraper(json_config, site_name_lower)
> File "D:\OnlyFans-master\datascraper\main_datascraper.py", line 105, in start_datascraper
> names = main_helper.process_names(
> File "D:\OnlyFans-master\helpers\main_helper.py", line 641, in process_names
> result = module.start_datascraper(
> File "D:\OnlyFans-master\modules\onlyfans.py", line 159, in start_datascraper
> results = prepare_scraper(authed, site_name, item)
> File "D:\OnlyFans-master\modules\onlyfans.py", line 792, in prepare_scraper
> unrefined_set = pool.starmap(
> File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 372, in starmap
> return self._map_async(func, iterable, starmapstar, chunksize).get()
> File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
> raise self._value
> File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
> result = (True, func(*args, **kwds))
> File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 51, in starmapstar
> return list(itertools.starmap(args[0], args[1]))
> File "D:\OnlyFans-master\modules\onlyfans.py", line 1035, in media_scraper
> post_id = post_result.id
> AttributeError: 'dict' object has no attribute 'id'

Same thing as this, with scrape_paid_content: false

**Comment by newadventure079** [comment] 2021-05-28 18:09
In addition to `AttributeError: 'list' object has no attribute 'id'`, I also noticed the model choice menu is gone now.  It just goes straight into scraping as if you pressed `0`

```
Welcome xxxxxxxxx | xxxxxxxxx
Scraping Paid Content
Scraping - sexbydesign | 1 / 58
Scraping [photo]. Should take less than a minute.
```

**Comment by Gixxa** [comment] 2021-05-28 19:59
@newadventure079 

I can not confirm that. I still see the model list and have to press a number.

**Comment by DIGITALCRIMINAL** [comment] 2021-05-28 21:43
Scraping paid_content should be fixed now

**Comment by valdearg** [comment] 2021-05-28 21:53
Getting the below error with the latest commit

```Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 99, in start_datascraper
    subscription_list = module.format_options(subscription_array, "usernames", api.auths)
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 1482, in format_options
    subscriber = x.get_subscriber(match_list)
  File "G:\Scripts\OnlyFans\apis\onlyfans\classes\create_user.py", line 218, in get_subscriber
    subscribes = self.subscribedByData["subscribes"][-1]
IndexError: list index out of range
```

**Comment by DIGITALCRIMINAL** [comment] 2021-05-28 21:55
> Getting the below error with the latest commit
> 
> ```Traceback (most recent call last):
>   File "G:\Scripts\OnlyFans\start_ofd.py", line 44, in <module>
>     api = main_datascraper.start_datascraper(json_config, site_name_lower)
>   File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 99, in start_datascraper
>     subscription_list = module.format_options(subscription_array, "usernames", api.auths)
>   File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 1482, in format_options
>     subscriber = x.get_subscriber(match_list)
>   File "G:\Scripts\OnlyFans\apis\onlyfans\classes\create_user.py", line 218, in get_subscriber
>     subscribes = self.subscribedByData["subscribes"][-1]
> IndexError: list index out of range
> ```

Do you know which user it's trying to access?

**Comment by valdearg** [comment] 2021-05-28 21:56
Sorry, I'm not sure, it's just after the login part:

Auth (V1) Attempt 1/10
Welcome Valdearg | uxxxxxxxx
Traceback (most recent call last):

**Comment by HtomSirveaux** [comment] 2021-05-28 21:58
I'm getting same error I was getting with scrape_paid_content: false before the fix.

`Traceback (most recent call last):
  File "/media/V_Drive/OnlyFans/start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/media/V_Drive/OnlyFans/datascraper/main_datascraper.py", line 105, in start_datascraper
    names = main_helper.process_names(
  File "/media/V_Drive/OnlyFans/helpers/main_helper.py", line 641, in process_names
    result = module.start_datascraper(
  File "/media/V_Drive/OnlyFans/modules/onlyfans.py", line 159, in start_datascraper
    results = prepare_scraper(authed, site_name, item)
  File "/media/V_Drive/OnlyFans/modules/onlyfans.py", line 795, in prepare_scraper
    unrefined_set = pool.starmap(
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/media/V_Drive/OnlyFans/modules/onlyfans.py", line 1038, in media_scraper
    post_id = post_result.id
AttributeError: 'dict' object has no attribute 'id'`

**Comment by DIGITALCRIMINAL** [comment] 2021-05-28 23:18
> Sorry, I'm not sure, it's just after the login part:
> 
> Auth (V1) Attempt 1/10
> Welcome Valdearg | uxxxxxxxx
> Traceback (most recent call last):

Are you a creator?

**Comment by headphonia** [comment] 2021-05-28 23:51
I'm getting the same error. I'm not a creator.

**Comment by myotheraccount420** [comment] 2021-05-29 01:00
```
Traceback (most recent call last):
  File "Z:\Recycle Bin\OnlyFans-master\start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "Z:\Recycle Bin\OnlyFans-master\datascraper\main_datascraper.py", line 99, in start_datascraper
    subscription_list = module.format_options(subscription_array, "usernames", api.auths)
  File "Z:\Recycle Bin\OnlyFans-master\modules\onlyfans.py", line 1482, in format_options
    subscriber = x.get_subscriber(match_list)
  File "Z:\Recycle Bin\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 219, in get_subscriber
    subscribes = self.subscribedByData["subscribes"][-1]
IndexError: list index out of range
```

`self.subscribedByData["subscribes"]`  returns an empty array so [-1] is out of bounds.

self.subscribedByData:
```
{'price': 4.99, 'newPrice': 4.99, 'regularPrice': 4.99, 'subscribePrice': 4.99, 'discountPercent': 0, 'discountPeriod': 1, 'subscribeAt': '2021-03-28T07:03:30+00:00', 'expiredAt': '2021-05-28T07:04:04+00:00', 'renewedAt': None, 'discountFinishedAt': None, 'discountStartedAt': None, 'status': 'Set to Expire', 'isMuted': False, 'unsubscribeReason': 'No reason given', 'duration': ' 2 months', 'showPostsInFeed': True, 'subscribes': []}
```

**Comment by DIGITALCRIMINAL** [comment] 2021-05-29 01:05
Thanks, are you subscribed to the user? Did you turn off auto renew?

**Comment by myotheraccount420** [comment] 2021-05-29 01:08
Let me do a little more digging. I'm getting this error right after the Welcome <username> message.

I think its safe to assume that I am subscribed and I do not have auto renew enabled for 99% of the creators I follow.

**Comment by myotheraccount420** [comment] 2021-05-29 01:21
Actually, I set `auto_model_choice` to `false` and am still getting the error so it's happening while parsing the available creator profiles.

Sorry if I speak incorrectly or out of order, I am new to the codebase and python is not my strong-suit, been about a decade since I have used it.

Okay, so I did a bit more research. It appears that OnlyFans is returning an account under 'Active' that has already expired.

**Comment by DIGITALCRIMINAL** [comment] 2021-05-29 01:35
Ahh okay I see now. I've removed the get_subscriber function in the latest commit. Script will no longer run into that error.

**Comment by myotheraccount420** [comment] 2021-05-29 01:36
I'll pull master and report back.

**Comment by newadventure079** [comment] 2021-05-29 01:49
It processes one model fine but then the next one produces this error. I chose `0` to process all models after I got the menu.

```
Scrape Processing
Name: angela_ride
Type: Profile
0.00B [00:00, ?B/s]
Type: Stories
Scraping [photo]. Should take less than a minute.
Traceback (most recent call last):
  File "/Users/Documents/code/OnlyFans/start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Users/Documents/code/OnlyFans/datascraper/main_datascraper.py", line 105, in start_datascraper
    names = main_helper.process_names(
  File "/Users/Documents/code/OnlyFans/helpers/main_helper.py", line 641, in process_names
    result = module.start_datascraper(
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 159, in start_datascraper
    results = prepare_scraper(authed, site_name, item)
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 795, in prepare_scraper
    unrefined_set = pool.starmap(
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 1038, in media_scraper
    post_id = post_result.id
AttributeError: 'dict' object has no attribute 'id'
```

**Comment by myotheraccount420** [comment] 2021-05-29 01:58
I think I see whats going on for me at least.

The first profile has no stories, or at least the scraper does not attempt to scrape them. 

I put a `print(type(post_result))`  above line 1038 in modules/onlyfans.py and I can see that for all other scrapes i'm getting a type of `onlyfans.classes.<x>` but for stories its returning a dict.

**Comment by DIGITALCRIMINAL** [comment] 2021-05-29 02:00
I'm fixing part of the problem. For me, it's to do with highlights.

**Comment by DIGITALCRIMINAL** [comment] 2021-05-29 02:24
Should be fixed now.

**Comment by myotheraccount420** [comment] 2021-05-29 02:28
Pulled master, confirmed working.

**Comment by newadventure079** [comment] 2021-05-29 03:48
I got the same error but in the section where it downloads the media

```
Download Processing
Name: jessikagotti | Type: Posts | Count: 3595 Images | Directory: /Volumes/P-Holding/onlyfans_rips

0it [00:00, ?it/s]Traceback (most recent call last):
  File "/Users/Documents/code/OnlyFans/start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/Users/Documents/code/OnlyFans/datascraper/main_datascraper.py", line 114, in start_datascraper
    x = main_helper.process_downloads(api, module)
  File "/Users/Documents/code/OnlyFans/helpers/main_helper.py", line 652, in process_downloads
    module.download_media(auth, subscription)
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 1259, in __init__
    pool.starmap(
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 1331, in prepare_download
    unrefined_set = media_scraper(
  File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 1036, in media_scraper
    post_id = post_result.id
AttributeError: 'list' object has no attribute 'id'
```

**Comment by DIGITALCRIMINAL** [comment] 2021-05-29 03:54
> I got the same error but in the section where it downloads the media
> 
> ```
> Download Processing
> Name: jessikagotti | Type: Posts | Count: 3595 Images | Directory: /Volumes/P-Holding/onlyfans_rips
> 
> 0it [00:00, ?it/s]Traceback (most recent call last):
>   File "/Users/Documents/code/OnlyFans/start_ofd.py", line 44, in <module>
>     api = main_datascraper.start_datascraper(json_config, site_name_lower)
>   File "/Users/Documents/code/OnlyFans/datascraper/main_datascraper.py", line 114, in start_datascraper
>     x = main_helper.process_downloads(api, module)
>   File "/Users/Documents/code/OnlyFans/helpers/main_helper.py", line 652, in process_downloads
>     module.download_media(auth, subscription)
>   File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 1259, in __init__
>     pool.starmap(
>   File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
>     return self._map_async(func, iterable, starmapstar, chunksize).get()
>   File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
>     raise self._value
>   File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
>     return list(itertools.starmap(args[0], args[1]))
>   File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 1331, in prepare_download
>     unrefined_set = media_scraper(
>   File "/Users/Documents/code/OnlyFans/modules/onlyfans.py", line 1036, in media_scraper
>     post_id = post_result.id
> AttributeError: 'list' object has no attribute 'id'
> ```

Ahh yee, basically the download failed so it tries to fetch the media again. Are you using a proxy?

**Comment by newadventure079** [comment] 2021-05-29 04:15
No, I'm not using a proxy

**Comment by DIGITALCRIMINAL** [comment] 2021-05-29 04:46
Try the latest commit.

**Comment by newadventure079** [comment] 2021-05-29 06:22
It works great! Thanks!

**Closed** 2021-05-29 06:23 UTC
Labels: patching
